- name: Add the 1st tuleap repo
  apt_repository: repo='deb http://pkg.tuleap.net/debian tuleap-dev main' state=present

- name: Add the 2nd tuleap repo
  apt_repository: repo='deb http://ftp.de.debian.org/debian wheezy-backports main' state=present

- name: apt install prerequisites
  apt: name="{{ item }}" update_cache=yes state=present
  with_items:
   - tuleap-archive-keyring
   - tuleap-all
